# Change these first
owner: susupaa # Your GitHub organization or username, where this repository lives
repo: susupaa-uptime # The name of this repository

sites:
  - name: Susupaa.com
    url: https://www.susupaa.com
    assignees:
      - Drake669
  - name: Susupaa API
    url: https://api.susupaa.com/health
    assignees:
      - noelzappy

  - name: Collectors Dashboard
    url: https://app.susupaa.com
    assignees:
      - Drake669

  - name: Checkout Portal
    url: https://checkout.susupaa.com
    assignees:
      - Drake669

  - name: Pay Portal
    url: https://pay.susupaa.com
    assignees:
      - Drake669

assignees: # Users to assign downtime issues (optional)
  - susupaa
  - noelzappy
  - Drake669

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.susupaa.com
  # baseUrl: /susupaa-uptime
  logoUrl: https://app.susupaa.com/assets/logo-iHr_AhoL.jpeg
  name: Susupaa Uptime
  introTitle: Susupaa Uptime Status
  introMessage: This page shows the status of all services provided by Susupaa.
    If you have any questions, please contact us at <a href="mailto:info@susupaa.com">
  navbar:
    - title: Home
      href: https://www.susupaa.com
    - title: Collectors Dashboard
      href: https://app.susupaa.com
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
